### ISSUE TITLE
pb-mathjax readme directions should be updated

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/pb-mathjax#68]
I spent some time today trying to install pb-mathjax using the installation instructions from the Readme file. I was doing the "single server" version where you set up a microservice on your existing pressbooks server.

NodeJS 10 has reached its end of life, and while you can still download it, the install script included will fail because dependencies used during installation have also reached end of life.

![Screen Shot 2022-06-14 at 4 16 55 PM](https://user-images.githubusercontent.com/29982981/173680822-2cad8c42-a456-4f0e-a593-73b1e469434e.png)

**Comment by beckej13820** [comment]
The installation also fails with NodeJS 16 LTS and NodeJS 14LTS which are the oldest LTS version of NodeJS still in security support.

Installation still works with NodeJS 12, but that is probably not recommended because it has reached end of life.

**Comment by beckej13820** [comment]
here is the error message I got from the "npm install" step when using NodeJS 14 

> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
> gyp ERR! System Linux 3.10.0
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/jelastic/pb-mathjax-master/node_modules/sharp
> gyp ERR! node -v v14.19.3
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the sharp@0.22.1 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2022-06-15T17_59_42_154Z-debug.log

**Comment by beckej13820** [comment]
What does the "cool down" label mean?

**Comment by SteelWagstaff** [comment]
Hi Ed -- it means that this is considered a good issue for one of our 'cool down' sprints, where developers can pick any issue from the backlog that interests them for improvement instead of focusing on a specific sprint goal directed by the product owner and accepted by the scrum team.

**Comment by beckej13820** [comment]
Thanks! I was worried it meant, "This aspect of pressbooks is no longer going to be supported for open-source users" and then died a little bit inside while I wondered what was going on for 24 days!

**Comment by SteelWagstaff** [comment]
Sorry about leaving you hanging like that -- I didn't see your comment until yesterday (got lost in the general firehose of information). We do want to update install instructions and NPM version support for this repo when we have a chance.

**Comment by beckej13820** [comment]
Don't be sorry! It's not your job to responsibly handle my anxiety! :-D

**Comment by SteelWagstaff** [comment]
@beckej13820 We are preparing a new release of MathJax in the next month or so, and will update the readme to accompany that. Thanks for your patience!

**Comment by SteelWagstaff** [comment]
Updated with latest release!
